apiVersion: v2
appVersion: 2.10.0
description: Grafana Tempo Single Binary Mode
home: https://grafana.net
icon: https://raw.githubusercontent.com/grafana/tempo/main/cmd/tempo/app/static/tempo-icon.png
maintainers:
- email: sheikhabubaker761@gmail.com
  name: Mohammad Abubaker
  url: https://github.com/Sheikh-Abubaker
name: tempo
sources:
- https://github.com/grafana/tempo
type: application
version: 1.26.1
