apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  entryPoints:
  - privateweb
  - privatesecure
  routes:
  - kind: Rule
    match: Host(`grafana.ftzmlab.xyz`)
    services:
    - name: kube-prometheus-stack-grafana
      port: 80
