apiVersion: v1
data:
  admin-password: Q1hmMUFwZFpWemdQaFJVSG1HcXF3SkVwUFNLR1hyZWtCa3ZXc1NxbQ==
  admin-user: YWRtaW4=
  ldap-toml: ""
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: admin-secret
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 12.3.2
    helm.sh/chart: grafana-11.0.1
  name: kube-prometheus-stack-grafana
  namespace: monitoring
type: Opaque
