apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: nfs-subdir-external-provisioner
    app.kubernetes.io/managed-by: Helmraiser
    chart: nfs-subdir-external-provisioner-4.0.18
    heritage: Helm
    release: nfs-provisioner
  name: leader-locking-nfs-provisioner-nfs-subdir-external-provisioner
  namespace: nfs-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-locking-nfs-provisioner-nfs-subdir-external-provisioner
subjects:
- kind: ServiceAccount
  name: nfs-provisioner-nfs-subdir-external-provisioner
  namespace: nfs-provisioner
