apiVersion: v1
data:
  runtime-config.yaml: |
    {}
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: loki
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: loki
    app.kubernetes.io/version: 3.6.4
    helm.sh/chart: loki-6.52.0
  name: loki-runtime
  namespace: monitoring
