apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: loki
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: loki
    app.kubernetes.io/version: 3.6.5
    helm.sh/chart: loki-6.53.0
  name: loki
  namespace: monitoring
