apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: loki
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: loki
    app.kubernetes.io/version: 3.6.4
    helm.sh/chart: loki-6.52.0
    prometheus.io/service-monitor: "false"
    variant: headless
  name: loki-headless
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 3100
    protocol: TCP
    targetPort: http-metrics
  selector:
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki
