apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: nfs-subdir-external-provisioner
    app.kubernetes.io/managed-by: Helmraiser
    chart: nfs-subdir-external-provisioner-4.0.18
    heritage: Helm
    release: nfs-provisioner
  name: nfs-provisioner-nfs-subdir-external-provisioner
  namespace: default
