apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: sealed-secrets
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: sealed-secrets
    app.kubernetes.io/part-of: sealed-secrets
    app.kubernetes.io/version: 0.34.0
    helm.sh/chart: sealed-secrets-2.18.0
  name: sealed-secrets-metrics
  namespace: sealed-secrets
spec:
  ports:
  - name: metrics
    nodePort: null
    port: 8081
    targetPort: metrics
  selector:
    app.kubernetes.io/instance: sealed-secrets
    app.kubernetes.io/name: sealed-secrets
  type: ClusterIP
