apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/instance: sealed-secrets
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: sealed-secrets
    app.kubernetes.io/part-of: sealed-secrets
    app.kubernetes.io/version: 0.34.0
    helm.sh/chart: sealed-secrets-2.18.0
  name: sealed-secrets-service-proxier
  namespace: sealed-secrets
rules:
- apiGroups:
  - ""
  resourceNames:
  - sealed-secrets
  resources:
  - services
  verbs:
  - get
- apiGroups:
  - ""
  resourceNames:
  - 'http:sealed-secrets:'
  - http:sealed-secrets:http
  - sealed-secrets
  resources:
  - services/proxy
  verbs:
  - create
  - get
