apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-34.5.0
  name: traefik
  namespace: traefik
